# Deep Learning via ANN

## Importing libraries

In [3]:
import pandas as pd 
import numpy as np 
import tensorflow as tf

In [4]:
tf.__version__

'2.20.0'

## Importing dataset

In [7]:
data_set = pd.read_csv("American Express User Exit Pred.csv")
X = data_set.iloc[:, 0:-1].values
y = data_set.iloc[:, -1].values

In [ ]:
print(X)

In [9]:
print(y)

[0 0 0 ... 0 1 0]


## Encoding categorical data

### Gender column : Label Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
X[:, 2] = lb.fit_transform(X[:, 2])

In [11]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


### Geography column : One hot Encoding

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


## Splitting dataset into Training & Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size=0.2 , random_state=0)

## Feature Scaling

## ANN

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
print(X_train.shape)
print(type(X_train))

(7941, 11)
<class 'numpy.ndarray'>


In [ ]:
print(X_test)

In [25]:
print(y_train)

[0 0 0 ... 1 1 0]


### Initialization

In [31]:
ann = tf.keras.models.Sequential()

### Adding input layer and first hidden layer

In [32]:
ann.add(tf.keras.layers.Dense(units = 5 , activation = 'relu', input_dim = 11))

### Adding second hidden layer

In [33]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

### Adding output layer

In [34]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## ANN Training

### Compiling ANN

In [35]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

### Training on training dataset

In [ ]:
ann.fit(X_train , y_train , batch_size=32 , epochs=100)

### Single Prediction

In [37]:
print(ann.predict(sc.transform(np.array([[0.0, 1.0, 0.0, 501 , 0 , 32, 2, 0.0 , 4 , 1 , 545501]]))) > 0.5 )

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
[[False]]


### Predication on testset

In [38]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1) , y_test.reshape(len(y_test),1)) , 1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


### Confusion Matrix

In [40]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
accuracy_score(y_test , y_pred)

[[1501   72]
 [ 259  154]]


0.8333333333333334